Controllers/AuthorizeController.cs
using Beehive.Models;
using Beehive.Models.DbRecords;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.SignalR;
using System.Security.Cryptography;

namespace Beehive.Controllers
{
    public class AuthorizeController : Controller
    {
        readonly ApplicationContext db;
        readonly IHubContext<DirectHub> hub;

        static private ApplicationContext database = null!;

        public AuthorizeController(ApplicationContext appContext, IHubContext<DirectHub> hubContext)
        {
            db = appContext;
            hub = hubContext;
            database = appContext;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddUser(RegisterModel am)
        {
            if (!am.ArePasswordsEqual || am.Name is null)
            {
                ViewBag.Message = "Пароли не совпадают";
                return View("Register");
            }
            if (db.Users.Any(u => u.Email == am.Email))
            {
                ViewBag.Message = "Данный e-mail занят";
                return View("Register");
            }
            var pass = am.EncryptPassword();
            var rsa = RSA.Create();
            var k = Rfc2898DeriveBytes.Pbkdf2(am.Password, am.Salt, 270000, HashAlgorithmName.SHA512, 128);
            var priv = rsa.ExportEncryptedPkcs8PrivateKey(k, new PbeParameters(PbeEncryptionAlgorithm.Aes256Cbc, 
                HashAlgorithmName.SHA256, 270000));
            var user = new UserRecord()
            {
                Pbkdf2 = pass,
                Id = Guid.NewGuid(),
                Name = am.Name,
                Email = am.Email,
                Salt = am.Salt,
                PublicKey = rsa.ExportRSAPublicKey(),
                EncryptedPrivateKey = priv
            };
            rsa.Dispose();
            db.Users.Add(user);
            db.SaveChanges();
            GlobalVals.WritePasskey(user.Id, k);
            Authorize(user);
            return new RedirectToActionResult("Search", "Direct", new { query = "" }); //STUB
        }

        internal static byte[] GetSalt(string email)
        {
            try
            {
                return database.Users.First(e => e.Email == email).Salt;
            }
            catch
            {
                throw new NotImplementedException();
            }
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult LogUser(AuthModel am)
        {
            var user = db.Users.FirstOrDefault(u => u.Email == am.Email);
            if (user is null)
            {
                ViewBag.Message = "Пользователь не найден";
                return View("Login");
            }
            if (!user.Pbkdf2.Zip(am.EncryptPassword()).All(e => e.First == e.Second))
            {
                ViewBag.Message = "Неверный пароль";
                return View("Login");
            }
            Authorize(user);
            return new RedirectToActionResult("Search", "Direct", new { query = "" }); //STUB
        }

        [Authorize]
        [HttpPost]
        public IActionResult LogOut()
        {
            var g = HttpContext.User.FindFirst(ClaimTypes.Name)!.Value;
            Models.User.Current.Remove(g);
            Models.User.CurrentRecord.Remove(g);
            HttpContext.SignOutAsync();
            return RedirectToAction("Login");
        }

        async void Authorize(UserRecord am) 
        {
            var guid = am.Id.ToString();
            var claims = new List<Claim> { new(ClaimTypes.Name, guid), new(ClaimTypes.NameIdentifier, guid) };
            var id = new ClaimsIdentity(claims, "Cookies");
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(id));
            Models.User.Current[guid] = new User(am);
            Models.User.CurrentRecord[guid] = am;
        }
    }
}

Views/Shared/TwoParter.cshtml
@{
    Layout = "_Layout";
}

<table id="two-part-layout">
    <tr>
        <td id="two-parter-left" width="75%">
            @RenderSection("Left")
        </td>
        <td id="two-parter-right" width="25%">
            @RenderSection("Right")
        </td>
    </tr>
</table>

@RenderSection("Scripts")

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Beehive</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Beehive.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Beehive</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Chat" asp-action="Search">Чаты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Direct" asp-action="Search">Сообщения</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Notifications">Уведомления</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Map">Карта</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Profile">Профиль</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Settings">Настройки</a>
                        </li>
                        <li class="nav-item">
                            <form method="post" asp-controller="Authorize" asp-action="LogOut">
                                <input type="submit" class="nav-link text-dark" value="Выйти">
                            </form>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header> 
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Beehive - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> 
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>